### ISSUE TITLE
Snapshots aren't tested for consistency?

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/cardano-haskell#31]
https://github.com/input-output-hk/cardano-haskell/blob/ba67e1da1bcef59c76f2f86f3f60c825e5c41e8b/snapshots/cardano-1.20.0.yaml#L3

https://github.com/input-output-hk/cardano-haskell/blob/ba67e1da1bcef59c76f2f86f3f60c825e5c41e8b/snapshots/cardano-1.20.0.yaml#L110-L111

1. lts-14.25 includes [ip-1.5.1](https://www.stackage.org/lts-14.25/package/ip-1.5.1)
2. cardano-sl-x509 commit `43a036c5bbe68ca2e9cbe611eab7982e2348fe49` does not build with ip-1.5.1: https://github.com/input-output-hk/cardano-sl-x509/pull/4

So the only reason we haven't seen this come up, afais, is that we don't actually depend on it. If I add `cardano-sl-x509` explicitly to e.g. cardano-wallet-core.cabal library section, it [fails to build](https://gist.github.com/hasufell/17854ddfc9aa14897b6bb6e10069129b) (also note the warning: `WARNING: Ignoring cardano-sl-x509's bounds on ip (==1.4.*); using ip-1.5.1.`)

This suggest we don't actually build all packages in the snapshot in one go. Does anyone know how stack does this for stackage?

**Comment by rvl** [comment]
You're correct - we don't actually build all packages in the snapshot in one go. Why would we want to do this?

Stackage snapshots have a build process that ensures everything works together, including tests passing. Packages which don't build or pass tests are dropped from the snapshot until they are fixed.

These yaml files make changes to the LTS snapshot which mean that the Stackage Curators' guarantees no longer apply. They are coherent enough for cardano-wallet to build with stack, and that's pretty much all we care about.

If you have a specific need, then make a PR to modify the snapshot.
